### ISSUE TITLE
Webp

### ISSUE THREAD

**Issue by Brand3000** [ctessier/nova-advanced-image-field#106]
Hello! As the webp format is getting more and more popular, it'd be great to add this format to your beautiful plugin.
Additionally, I'd like to have an opportunity to store the original file as well. It's very useful in a regular CMS.

**Comment by Ruitjes** [comment]
I also really need this feature, ~~sadly I do hot have the capacity or the knowledge to implement this.~~ working on it.

**Comment by Ruitjes** [comment]
Hi @Brand3000 I just added the possibility to format images to the webp format. Maybe you can check the PR as-well.
