### ISSUE TITLE
CORS error when editing

### ISSUE THREAD

**Issue by Ruitjes** [ctessier/nova-advanced-image-field#111]
I'm encountering a CORS error when editing. On the details page, the images display correctly, but when I try to edit, I receive CORS errors.

On the view page:
![image](https://github.com/user-attachments/assets/f6fc277e-bb65-4d09-97bc-74a9149ba1e3)

When editing:
![image](https://github.com/user-attachments/assets/2d4d1b85-2eb8-4d6a-a731-6903d5d1e5d3)

After clearing the cache, the images load as intended, so I suspect the issue might be related to caching.

**Comment by ctessier** [comment]
Hi @Ruitjes 

I am not sure to see how this is related to the package, but rather your storage configuration.

Have you tried setting CORS configuration within your S3 storage config?

**Comment by Ruitjes** [comment]
Hi @ctessier, I'm quite certain it's not a CORS configuration since I'm allowing everything. I'll have to deep a bit deeper, will fork the PR to check it out and let you know.
