### ISSUE TITLE
check and save mime

### ISSUE THREAD

**Issue by h-zone** [ctessier/nova-advanced-image-field#21]
Hello!
I'm asking to make follow abilities:
- check for allowed mime types [optional, turnable]. it can be readable resource property (array)
- save uploaded and verified mime result into additional field of the same table [optional, turnable]

i.e. result:
id | filename | mime
 1 | Image.jpg | image/jpeg

this feature is usable when used non listed disk storages and/or custom file download algorithms.

**Comment by ctessier** [comment]
Hey @h-zone, 

Good news! Checkout the new [v1.2.0](https://github.com/ctessier/nova-advanced-image-field/releases/tag/v1.2.0) release which provides you with all the File's methods, including `storeAs` where you can customize the name, and `store` to add a custom attribute for the mime-type! The field now also only accept files of image's mime-types!

Do not hesitate to give me feedback if this fixes your problem!

Have a great day,
Clément
