### ISSUE TITLE
ability to rename image too

### ISSUE THREAD

**Issue by h-zone** [ctessier/nova-advanced-image-field#22]
need abilities:
- to rename image at nova
- to set random filename instead storing the real name.
- prevent to store non alphanumeric file names (i.e. file names in non english language, with spaces ad/or other special symbols)
Explaining
```php
$hash = str_random(16); // dnfybfXBjZcSjuIk
$path = "/dn/"
$filename = "dnfybfXBjZcSjuIk" . $extension_from_mime_type;
$file = $path.$filename; // "/dn/dnfybfXBjZcSjuIk.PNG"
```

**Comment by ctessier** [comment]
Hi @h-zone,

This feature will be available in the next release of the field. This release will fix many issues with the inheritance of the native File field, including access to methods like `store` and `storeAs` allowing you to customize the filename.

See https://nova.laravel.com/docs/3.0/resources/file-fields.html#customizing-file-storage

Have a good one!
Clément

**Comment by ctessier** [comment]
Hey @h-zone, 

This is now made possible in the new [v1.2.0](https://github.com/ctessier/nova-advanced-image-field/releases/tag/v1.2.0) release 

Check it out and let me know!

Clément
