### ISSUE TITLE
thumbnail generation?

### ISSUE THREAD

**Issue by h-zone** [ctessier/nova-advanced-image-field#24]
Hi!
im lost.
Just now I saw that the thumbnail is not generated.
Any idea how to solve this problem?

**Comment by ctessier** [comment]
Hi @h-zone,
Do you still have this issue?
Can you please provide more details?
Thank you

**Comment by h-zone** [comment]
Hi @ctessier im using medialibrary for now.
thank, all fine ))

**Comment by ctessier** [comment]
Thanks for your feedback. Closing then.
