### ISSUE TITLE
Don't work store() method

### ISSUE THREAD

**Issue by blaqdog** [ctessier/nova-advanced-image-field#26]
Laravel 5.8
I am trying to make crop and resize of an image and store it with spatie/laravel-medialibrary package

the code that works without AdvancedImage:
```php
Image::make('Image 100x100', 'image')
    ->store(function (Request $request, $model) {
        // if isset then remove
        $mediaItem = $model->getMedia('shortcut')->first();
        if($mediaItem){
            $mediaItem->delete();
        }
        // saving new image
        $model->addMediaFromRequest('image')
            ->toMediaCollection('shortcut');
    })
    ->delete(function (Request $request, $model) {
        $mediaItem = $model->getMedia('shortcut')->first();
        if($mediaItem){$mediaItem->delete();}
    })
    ->preview(function () {
        return $this->getFirstMediaUrl('shortcut');
    })
    ->thumbnail(function () {
        return $this->getFirstMediaUrl('shortcut');
    })
    ->deletable(true),
```

The code to make crop using AdvancedImage:
```php
AdvancedImage::make('Image', 'image')
    ->store(function (Request $request, $model) {
        // if isset then remove
        $mediaItem = $model->getMedia('shortcut')->first();
        if($mediaItem){
            $mediaItem->delete();
        }
        // saving new image
        $model->addMediaFromRequest('image')
            ->toMediaCollection('shortcut');
    })
    ->croppable(1/1)->resize(100, 100)
    
    ->delete(function (Request $request, $model) {
        $mediaItem = $model->getMedia('shortcut')->first();
        if($mediaItem){$mediaItem->delete();}
    })
    ->preview(function () {
        return $this->getFirstMediaUrl('shortcut');
    })
    ->thumbnail(function () {
        return $this->getFirstMediaUrl('shortcut');
    })
    ->deletable(true),
```
Frontend part working great, but store() method dont work, so I cant using it in my project. 
Tried
```php
    ->store(function (Request $request, $model) {
        Log::info( json_encode($request) );
    })
```
This part is not called

**Comment by semihkeskindev** [comment]
laravel 7.0
`->storeAs()` method not working either.

**Comment by ctessier** [comment]
> laravel 7.0
> `->storeAs()` method not working either.

`storeAs()` is a Laravel 5.x method. Just like `store()`, it is provided by the `UploadedFile` class.

I have a fix ready that will make the field work just like the `File` field which uses the `UploadedFile` methods. Just need to be a bit patient until I fully tested it out.

**Comment by ctessier** [comment]
Hey @blaqdog and @semihkeskindev,

Good news! Checkout the news [v1.2.0](https://github.com/ctessier/nova-advanced-image-field/releases/tag/v1.2.0) release which provides you with all the File methods, including `store`!

Do not hesitate to give me feedback if this fixes your problem!

Have a great day,
Clément
