### ISSUE TITLE
path() method is not working

### ISSUE THREAD

**Issue by ste7** [ctessier/nova-advanced-image-field#27]
path() method is not working with AdvancedImage, it's always saved on root directory with random string

`AdvancedImage::make('Image')
                ->path('projects')
                ->croppable(16/9)`

Is there any solution?

Thanks!

**Comment by ctessier** [comment]
Hi @ste7,

The problem has already been exposed in #15. I provided an answer and hope to be able to work on it shortly.
I will let you know ;)

Cheers
