### ISSUE TITLE
Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files.

### ISSUE THREAD

**Issue by semchishinv** [ctessier/nova-advanced-image-field#33]
If image have .JPG instead .jpg this throw error in **Create/Edit** mode.

![image](https://user-images.githubusercontent.com/30542757/77138166-1ef3f100-6a9b-11ea-8fb7-8db4f4a579c8.png)

**Comment by ctessier** [comment]
Hi @semchishinv, 

First, thank you very much for your feedback!

I attempted to reproduce this bug but I couldn't not.
Can you please provide more details about your context (OS, GD version, ..) and if possible about the file itself?

Thank you! Have a great day!

**Comment by ctessier** [comment]
Hi @semchishinv,

As I didn't hear from you, I am going to close the issue.
Feel free to open a new one with more details if the problem persists.

Thank you!
Clément
