### ISSUE TITLE
storeOriginalName() failure

### ISSUE THREAD

**Issue by nukunet** [ctessier/nova-advanced-image-field#35]
Version: 1.0.2

use Ctessier\NovaAdvancedImageField\AdvancedImage;

I want to use this to get the original file name

`AdvancedImage::make('Photo', 'Image_Path')
                ->disk('public_Photo')
                ->croppable(1024 / 1024)
                ->resize(1024, 1024)
                ->storeOriginalName('Image_Original_Name'),`

normal work
`AdvancedImage::make('Photo', 'Image_Path')
                ->disk('public_Photo')
                ->storeOriginalName('Image_Original_Name'),`

failure
`AdvancedImage::make('Photo', 'Image_Path')
                ->disk('public_Photo')
                ->croppable(1024 / 1024)
                ->storeOriginalName('Image_Original_Name'),`

failure
`AdvancedImage::make('Photo', 'Image_Path')
                ->disk('public_Photo')
                ->resize(1024, 1024)
                ->storeOriginalName('Image_Original_Name'),`

**Comment by ctessier** [comment]
Hi @nukunet,

First, thank you very much for your feedback!

The `storeOriginalName` function should indeed work as it is provided by the native `File` Nova field.
Another issue is opened regarding a feature of the `File` field that do not work when using the cropping or resizing feature: #26.

I am sure working on that inheritance issue and am planning a release this summer that will fix those.

Hope this will help!
Have a great day,
Clément

**Comment by ctessier** [comment]
Hi @nukunet,

Good news! Checkout the news v1.2.0 release which provides you with all the `File` methods, included `storeOriginalName`!

Do not hesitate to let me know how it goes ;)

Have a good day,
Clément
