### ISSUE TITLE
Encoding format (tmp) is not supported.

### ISSUE THREAD

**Issue by NanoCellWebDesign** [ctessier/nova-advanced-image-field#52]
When updating an image using:

`   AdvancedImage::make('Image', 'img')
                ->hideFromIndex()
                ->hideWhenCreating()
                ->showOnUpdating()
                ->croppable(16/9)
                ->resize(1280/720)
                ->disk('public')
                ->path('/events/events/'.$this->id)
                ->prunable()
                ->disableDownload(),`

its gives me an error:

Encoding format (tmp) is not supported.

im using the GD lib and havent changed any other files. the default laravel nova image field works

**Comment by MiAlmeida** [comment]
Did you find a solution?

**Comment by ctessier** [comment]
Hi @NanoCellWebDesign,

This seems to be an issue with [Intervention/image](https://github.com/Intervention/image) itself. Please check out this: https://github.com/Intervention/image/issues/852

I am closing the issue as it is not related to this package.

Thanks for your feedback.
Clément

**Comment by NanoCellWebDesign** [comment]
> Did you find a solution?

nope

**Comment by ctessier** [comment]
The latest release might fix this issue. Let me know @MiAlmeida @RhysLees 😉 
Also let me know if you would like this fix to be backported into v1 for Nova < 4.

[v2.0.3](https://github.com/ctessier/nova-advanced-image-field/releases/tag/v2.0.3)
