### ISSUE TITLE
Use AdvancedImage as avatar

### ISSUE THREAD

**Issue by asivaneswaran** [ctessier/nova-advanced-image-field#53]
Is it possible to use AdvancedImage field as the avatar?

**Comment by ctessier** [comment]
Hi @asivaneswaran,

Thank you for your request.

What feature from the Avatar field would you like to use?

You can round the image using the `rounded()` method. If you want the image to show when using searcheable relationships, the field needs to implement the `Cover` class, which is tricky to make configurable.

Let me know and we can think of a solution.

Thank you
Clément

**Comment by ctessier** [comment]
Hi @asivaneswaran 

This feature has been added to [v1.3.0](https://github.com/ctessier/nova-advanced-image-field/releases/tag/v1.3.0).

Have a good day.
