### ISSUE TITLE
RTL Problem

### ISSUE THREAD

**Issue by amidesfahani** [ctessier/nova-advanced-image-field#55]
Hi
Photo cropping plugin does not display properly

![Screenshot_1](https://user-images.githubusercontent.com/61671721/95891159-881db780-0d91-11eb-893e-50553f429bab.png)

- Nova 3.12
- RTL Theme: [nova-rtl-theme](https://github.com/pishran/nova-rtl-theme)

**Comment by ctessier** [comment]
Hi @amidesfahani,

Thank you for your feedback.

Unfortunately, I don't think it is possible to fix your issue from the package.
It seems to me that it is related to the `rtl` direction of the theme you are using. The Cropper.js library doesn't seem to handle this well.
I'd suggest your open an issue on their side, or workaround it by applying a custom CSS rule in your project to keep the field left-to-right.

Good luck 😉 
Clément
