### ISSUE TITLE
help does not show

### ISSUE THREAD

**Issue by mziraki** [ctessier/nova-advanced-image-field#56]
help text structure changed in new nova vue default field and needs to update to show again

**Comment by ctessier** [comment]
Hi @mziraki,
Thank for your feedback.
I will try to have a look asap. Do you have a screen maybe?

Feel free to submit PR if you have time ;)

Thank you

**Comment by mziraki** [comment]
> Hi @mziraki,
> 
> Thank for your feedback.
> I will try to have a look asap. Do you have a screen maybe?
> 
> Feel free to submit PR if you have time ;)
> 
> Thank you

fix: https://github.com/ctessier/nova-advanced-image-field/pull/57

**Comment by mziraki** [comment]
@ctessier plz check the PR, I need this fix ASAP
