### ISSUE TITLE
Have followed installation instructions but there is no crop option showing on my image.

### ISSUE THREAD

**Issue by keironwaites** [ctessier/nova-advanced-image-field#60]
Apologies for asking what seems like a support question here, but I have installed nova-advanced-image-field and I cannot see any ability to crop my image. Is ther a JavaScript compiling process which is missing from the installation instructions?

```
    public function fields(Request $request)
    {
        return [
            AdvancedImage::make('Image', 'file')
                ->croppable()
                ->disk('s3')
                ->path('data/photos/large')
        ];
    }
```

**Comment by keironwaites** [comment]
I have discovered the source of the problem. The crop option does not show on an image that already exists - only when you upload a new one. Is this expected behaviour?

**Comment by ctessier** [comment]
Hi @keironwaites,

Indeed, the crop is for when editing the picture. 
Choose your file, use the canvas to crop as per your convenience and validate to save the cropped file.

Thanks for reaching out.
Regards
