### ISSUE TITLE
Problem with wrong rotation of the images

### ISSUE THREAD

**Issue by eAvio** [ctessier/nova-advanced-image-field#62]
When uploading images taken with phone, orientation is sometimes wrong.

I found the solution to just add "orientate()" to:
`$this->image = Image::make($uploadedFile->getPathName())->orientate();`

After that it works fine.

Maybe it would be good idea to include this into the package.

Example image that rotates wrong is this:

![20201008_073926](https://user-images.githubusercontent.com/61407700/102524740-aeb1e480-4099-11eb-83f0-d78bec8cadd1.jpg)

**Comment by ctessier** [comment]
Hi @eAvio ! 

Thank you for your feedback! Check out #61, let me know if that can work for you.

Clément

**Comment by shaffe-fr** [comment]
Hi,
I tried the PR #61 on my project and it's working!

**Comment by ctessier** [comment]
Hi @eAvio 

This feature has been added to [v1.3.0](https://github.com/ctessier/nova-advanced-image-field/releases/tag/v1.3.0).

Have a good day.
