### ISSUE TITLE
Encoding format (tmp) is not supported 

### ISSUE THREAD

**Issue by MHassanSaqib** [ctessier/nova-advanced-image-field#72]
I am getting this error. I am on windows and according to stackoverflow, this is intervention error occurs at windows. Could you help me to resolve that, please? 

Thanks,

**Comment by ctessier** [comment]
Hi @MHassanSaqib,

Thank you for your feedback.
This issue was already answered in #52.

Let me know if you keep having troubles. I will try to help.

Clément

**Comment by ctessier** [comment]
The latest release might fix this issue. Let me know @MHassanSaqib  😉 
Also let me know if you would like this fix to be backported into v1 for Nova < 4.

[v2.0.3](https://github.com/ctessier/nova-advanced-image-field/releases/tag/v2.0.3)
