### ISSUE TITLE
Looking to make images that are cached bustable, use a query string 

### ISSUE THREAD

**Issue by dan-lutd** [ctessier/nova-advanced-image-field#77]
In node I am saving a query string with the epoch added as a query string to cause cache busting.  

`?16234234234`

Where i would do that with this plugin?

**Comment by ctessier** [comment]
Hi @dan-lutd 

Can you please be more specific? I don't see how that related to the package.

Thank you
Clément

**Comment by dan-lutd** [comment]
It is a non-issue since it will be a differnt filename every time the image is changed.
