### ISSUE TITLE
Is there a method to have multipul images per record?

### ISSUE THREAD

**Issue by dan-lutd** [ctessier/nova-advanced-image-field#78]
I am using the plugin for an image per record and now have to save multipule images per record.
Is there a way with this plugin to do that?

**Comment by ctessier** [comment]
Hi @dan-lutd 

If it fits your need, you can set multiple `AdvancedImage` fields to your resource:

```php
AdvancedImage::make('Photo 1');
AdvancedImage::make('Photo 2');
AdvancedImage::make('Photo 3');
```

If you want to upload multiple times the same image, you can have a look at #59, an already ongoing discussion.

Hoping this helps.
Clément
