### ISSUE TITLE
Encoding format (tmp) is not supported.

### ISSUE THREAD

**Issue by rezabrnt** [ctessier/nova-advanced-image-field#92]
Get the "Encoding format (tmp) is not supported" error when uploading.

**Comment by ctessier** [comment]
See #72

**Comment by ctessier** [comment]
The latest release might fix this issue. Let me know @rezabrnt 😉 

[v2.0.3](https://github.com/ctessier/nova-advanced-image-field/releases/tag/v2.0.3)
