### ISSUE TITLE
Argument 2 passed to Ctessier\NovaAdvancedImageField\AdvancedImage::transformImage() must be an object

### ISSUE THREAD

**Issue by yang20210404** [ctessier/nova-advanced-image-field#94]
Thanks for creating this package!

When I save form, I get this error
How to solve it? Thanks

![截圖 2023-02-08 上午11 46 12](https://user-images.githubusercontent.com/82806405/217440908-ff933ff6-3f72-46ac-940e-ef50aa994a72.png)

**Comment by ctessier** [comment]
Hi @yang20210404 

Thank you for your feedback.
Check out #89, it was merged this week. I will release a new version in the coming days. 

In the mean time, you can use the ´croppable´ method to ensure the second argument is not null.
