### ISSUE TITLE
Doesn't work on a hosting

### ISSUE THREAD

**Issue by Brand3000** [ctessier/nova-advanced-image-field#95]
Hi! Everything is fine on my local computer. But the plugin doesn't want to work after uploading my finished website to the hosting. 
When I'm choosing an image, the interface for cropping just doesn't appear. =( Could somebody give me a hint, please?

**Comment by ctessier** [comment]
Hi @Brand3000 

Do you see any error in the console?
What version of the package are you using?
Make sure you call the ´croppable()' method on your field.

Let me know ;)

**Comment by Brand3000** [comment]
No, no errors. The blob request doesn't happen in the console.
And unfortunately, while I was digging in the issue, it happened on my local copy as well. =(

**Comment by ctessier** [comment]
OK
You should be a little more specific though...

Which version of Nova? What error do you get, if any? What does you resource class look like? What is your version of PHP?

**Comment by ctessier** [comment]
See #96
